services:
  rma-web:
    container_name: rma-web
    build:
      context: .
      dockerfile: Dockerfile
    image: rma-web:next
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rma-web.rule=Host(`rma.preview.nayagrowth.com`)"
      - "traefik.http.routers.rma-web.entrypoints=websecure"
      - "traefik.http.routers.rma-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.rma-web.loadbalancer.server.port=3000"

networks:
  proxy_net:
    external: true
