import type { PresenceContent } from "./presence.types";

export const presenceContent: PresenceContent = {
  sectionNumber: "03",
  sectionTitle: "BUILT PORTFOLIO",
  eyebrow: "BUILT PORTFOLIO.",
  headline: "Landmark Developments",
  supportingNote:
    "Transforming high-end 3 & 4 BHK residences, bespoke villas, and boutique workspaces across Pune's finest developments and Lonavala retreats.",
  projects: [
    {
      id: "kolte-patil",
      number: "01",
      name: "Kolte Patil Projects",
      sublabel: "Luxury 3 & 4 BHK Full Home Interiors",
      image: "/landmarks/project-01-kolte-patil.webp",
      category: "RESIDENTIAL",
      href: "/resources",
    },
    {
      id: "godrej-infinity",
      number: "02",
      name: "Godrej Infinity",
      sublabel: "Contemporary Turnkey Living Spaces",
      image: "/landmarks/project-02-godrej-infinity.webp",
      category: "PREMIUM",
      href: "/resources",
    },
    {
      id: "koregaon-park",
      number: "03",
      name: "Koregaon Park",
      sublabel: "Bespoke Joinery & Architectural Styling",
      image: "/landmarks/project-03-koregaon-park.webp",
      category: "LUXURY",
      href: "/resources",
    },
    {
      id: "lonavala-villas",
      number: "04",
      name: "Lonavala Villas",
      sublabel: "Weekend Retreats & Landscape Integration",
      image: "/landmarks/project-04-lonavala-villas.webp",
      category: "RETREATS",
      href: "/resources",
    },
    {
      id: "bibewadi-estates",
      number: "05",
      name: "Bibewadi Estates",
      sublabel: "Complete Spatial & Structural Renovations",
      image: "/landmarks/project-05-bibewadi-estates.webp",
      category: "TURNKEY",
      href: "/resources",
    },
  ],
  studioName: "RMA",
  studioTagline: "RADHIKA MAHAJAN ARCHITECTS",
  // Backwards compatibility
  headlineWord1: "BUILT",
  headlineWord2: "PORTFOLIO",
  metaLabel: "Landmark Developments",
  signatures: [
    {
      id: "kolte-patil",
      name: "Kolte Patil Projects",
      sublabel: "Luxury 3 & 4 BHK Full Home Interiors",
      category: "RESIDENTIAL",
      iconType: "residence",
    },
    {
      id: "godrej-infinity",
      name: "Godrej Infinity",
      sublabel: "Contemporary Turnkey Living Spaces",
      category: "PREMIUM",
      iconType: "penthouse",
    },
    {
      id: "koregaon-park",
      name: "Koregaon Park",
      sublabel: "Bespoke Joinery & Architectural Styling",
      category: "LUXURY",
      iconType: "villa",
    },
    {
      id: "lonavala-villas",
      name: "Lonavala Villas",
      sublabel: "Weekend Retreats & Landscape Integration",
      category: "RETREATS",
      iconType: "retreat",
    },
    {
      id: "bibewadi-estates",
      name: "Bibewadi Estates",
      sublabel: "Complete Spatial & Structural Renovations",
      category: "TURNKEY",
      iconType: "turnkey",
    },
  ],
};

